name: spy_game
description: "Spy Game â€“ Spyfall multiplayer v3"
publish_to: "none"
version: 3.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^4.0.0
  provider: ^6.1.2
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  shared_preferences: ^2.2.3
  audioplayers: ^5.2.1
  vibration: ^1.8.4
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
